### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by AkioSarkiz** [Lavish098/DeeManga#1]
Hello! 

I am interested in development a manga website like you. What do you think about coop development? I can help you with the back-end part and I also can help you with the front-end part too. 

Look forward to your reply!

**Comment by Lavish098** [comment]
Hey!

I will be glad to coop with you.
I already have a backend API where I scrap data from mangareader. But I am currently having the an issue with viewing the manga chapter content.. I don't know much about backend am just lucky my changes are working... If you would be interested in looking at the backend for me I would appreciate it. Would also like some help with the styling cuz am too good with styling..

Thanks.

**Comment by AkioSarkiz** [comment]
Nice to hear it, do you have discord account or something else to communicate?

**Comment by AkioSarkiz** [comment]
Hello! What about my last message?
